version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Docker/Flask/Dockerfile
    container_name: flask-container
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  db:
    build:
      context: .
      dockerfile: Docker/MySQL/Dockerfile
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=SUN_Chaser
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=chaser
      - TZ=Asia/Tokyo
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./Docker/NginX/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  mysql-data:
