version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Docker/Flask/Dockerfile
    container_name: flask-container
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  mysql:
    build:
      context: .
      dockerfile: Docker/MySQL/Dockerfile
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=chaser
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./Docker/NginX/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask

volumes:
  mysql-data:
